# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - kyanite

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.18.2'

      - name: Installing Dependencies | APT | NPM | RUSH
        run: |
          sudo apt update
          sudo apt install git
          sudo apt install g++
          sudo apt install bash
          sudo apt --reinstall install bash
          sudo apt install make
          sudo apt install python3
          npm install -g pnpm
          npm install -g lerna
          npm install -g node-gyp
          npm install -g node-gyp-build
          npm install -g @microsoft/rush
          npm install -g ganache-cli
          npm install -g concurrently
          sudo apt install gettext
          rush update
          rush build

     # - name: Zip file Kyanite
     #   run: |
     #     zip kyanite.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .

  deploy:
    runs-on: self-hosted
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

     # - name: Unzip Kyanite for Deployment
     #   run: unzip kyanite.zip

     # - name: Delete Zip File
     #   run: rm kyanite.zip

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'kyanite'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_224048A4C95D45789F48BBF632AFE36C }}
          package: .